# 1. Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name YOUR_IP.sslip.io; # СЕРВЕР ЗАМЕНИТ ЭТО НА ТВОЙ IP

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. Основной HTTPS сервер
server {
    listen 443 ssl;
    server_name YOUR_IP.sslip.io; # СЕРВЕР ЗАМЕНИТ ЭТО НА ТВОЙ IP

    ssl_certificate /etc/nginx/live/fullchain.pem;
    ssl_certificate_key /etc/nginx/live/privkey.pem;

    # Отдаем React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование в Node.js (порт 5000, как у тебя в коде)
    location /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}